{% set name = "acwater" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6b68976cda51044c965c901acefc38c7b76a2cd34d0ebff2004a2e288d49975

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - acwater = acwater.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - geoarray
    - netcdf4
    - numpy
    - pandas
    - scipy

    # upstream Polymer dependencies
    - cdsapi
    - cython <3  # Polymer (4.16.1) cannot be compiled with Cython 3, see https://forum.hygeos.com/viewtopic.php?f=7&t=221&start=10
    - ecmwf-api-client
    - gdal
    - pygrib
    - pyhdf
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - acwater

about:
  home: https://gitlab.awi.de/phytooptics/acwater
  summary: ACwater Polymer implements a class to load an EnMAP object and execute atmospheric correction for water surfaces and requires EnPT for the EnMAP data processing.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alvaradobonilla
    - danschef
