{% set name = "acwater" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}  # polymer is not 3.10-compatible

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.awi.de/phytooptics/acwater/-/archive/v{{ version }}/acwater-v{{ version }}.tar.gz
  sha256: b267e4511fa71544c6bdec9a924f59c3e76209a6ea7d5f656081c233c9d77327

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - acwater = acwater.cli:main

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - enpt
    - polymer
    - netcdf4
    - numpy
    - pandas
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - acwater
    - enpt
    - polymer

about:
  home: https://gitlab.awi.de/phytooptics/acwater
  summary: Atmospheric correction of EnMAP hyperspectral data for water surfaces (ACwater), based on EnPT and Polymer.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josbel96
    - danschef
