{% set name = "acwater" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2f7744b4c34a57fb4b50d89ad9653b50c328a506c41303e691345f0afafdbc1c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - acwater = acwater.cli:main

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - netcdf4
    - geoarray 

test:
  imports:
    - acwater
 
about:
  home: https://gitlab.awi.de/phytooptics/acwater
  summary: ACwater Polymer implements a class to load an EnMAP object and execute atmospheric correction for water surfaces and requires EnPT for the EnMAP data processing.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alvaradobonilla
    - danschef
